-- Generated by scripts/import-canonical.mjs from the owner-approved
-- canonical dataset; do not edit by hand.
-- Stage 14G post-cutover additions: this forward migration adds ONLY
-- canonical rows whose id is absent from the frozen 0004_* seed, because
-- 0001-0006 are already recorded in the production migration ledger and
-- their file names can never re-run. Re-applying upserts by primary key.
-- canonical_csv_sha256=779f607cc8e5ca22daff2dde3b6ffff679a51607df6768cfb880d486c2d67b51
-- provenance_csv_sha256=943968b22853ac1fdac38b24ae33f88ca6f8ede2b66f7fb36bfd4b77aca0dd5a
-- additions_canonical_rows=1
-- additions_provenance_rows=2
-- reviewed record_status is preserved via COALESCE/NULLIF rather than CASE
-- WHEN, because Wrangler's SQL splitter treats a trailing `CASE ` as an
-- unclosed compound statement and merges the rest of the file into one
-- statement that local D1 then rejects with SQLITE_TOOBIG.

INSERT INTO canonical_locations (
  canonical_id, record_status, name, latitude, longitude, address, restroom_presence, bidet_presence, access, fee, restroom_verification, bidet_verification, candidate_priority, parent_venue, source_count, osm_type, osm_id, bidet_source_id, match_status, match_confidence, match_reason, last_checked, notes
) VALUES
('buttler_loc_e43982e95335d647d95c', 'candidate', 'Department of Information and Communications Technology', 9.3063328, 123.3088646, 'Bishop Epifanio B. Surban Street, Poblacion 3, Dumaguete City', 'Yes', 'Yes', 'unknown', 'unknown', 'field_verified_via_bidet_survey', 'field_verified', 'High', NULL, 2, 'node', '12566526394', 'bidet_survey_17faf0a4b26e748fbd3c', 'auto_matched_high_confidence', 'high', 'Owner field survey of 2026-10-01 and OSM node/12566526394 describe the same government office; the OSM location is correct and coordinates are unchanged.', NULL, 'Restroom and bidet presence confirmed by an owner firsthand field survey on 2026-10-01. Location evidence from OSM node/12566526394 (OSM itself records no toilet/bidet). Distinct from the separate public toilet roughly 52 m away.')
ON CONFLICT(canonical_id) DO UPDATE SET
  name = excluded.name,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  address = excluded.address,
  restroom_presence = excluded.restroom_presence,
  bidet_presence = excluded.bidet_presence,
  access = excluded.access,
  fee = excluded.fee,
  restroom_verification = excluded.restroom_verification,
  bidet_verification = excluded.bidet_verification,
  candidate_priority = excluded.candidate_priority,
  parent_venue = excluded.parent_venue,
  source_count = excluded.source_count,
  osm_type = excluded.osm_type,
  osm_id = excluded.osm_id,
  bidet_source_id = excluded.bidet_source_id,
  match_status = excluded.match_status,
  match_confidence = excluded.match_confidence,
  match_reason = excluded.match_reason,
  last_checked = excluded.last_checked,
  notes = excluded.notes,
  record_status = COALESCE(NULLIF(CAST(canonical_locations.record_status AS TEXT), 'candidate'), excluded.record_status),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');

INSERT INTO location_provenance (
  canonical_id, source_link_id, source_type, source_record_id, evidence_role, original_name, original_latitude, original_longitude, original_address, original_access, original_fee, original_restroom_presence, original_bidet_presence, verification, source_data_json
) VALUES
('buttler_loc_e43982e95335d647d95c', 'bidet_survey_17faf0a4b26e748fbd3c', 'field_survey_bidet_workbook', 'bidet_survey_17faf0a4b26e748fbd3c', 'verified_bidet_and_restroom_presence', 'Department of Information and Communications Technology', 9.3063328, 123.3088646, 'Bishop Epifanio B. Surban Street, Poblacion 3, Dumaguete City', 'unknown', 'unknown', 'Yes', 'Yes', 'field_verified', '{"Name":"Department of Information and Communications Technology","Latitude":9.3063328,"Longitude":123.3088646,"Address":"Bishop Epifanio B. Surban Street, Poblacion 3, Dumaguete City","Access":"unknown","Fee":"unknown","Bidet_Source_ID":"bidet_survey_17faf0a4b26e748fbd3c","Surveyed_On":"2026-10-01","SurveyedBy":"owner (firsthand visit)"}'),
('buttler_loc_e43982e95335d647d95c', 'node/12566526394', 'OSM', 'node/12566526394', 'restroom_acquisition', 'Department of Information and Communications Technology', 9.3063328, 123.3088646, 'Bishop Epifanio B. Surban Street, Poblacion 3, Dumaguete City', 'unknown', 'unknown', 'Unknown', 'Unknown', 'candidate_unverified', '{"Source":"OSM","Source_ID":"node/12566526394","OSM_Type":"node","OSM_ID":"12566526394","Name":"Department of Information and Communications Technology","Short_Name":"DICT","Office":"government","Government":"administrative","Latitude":9.3063328,"Longitude":123.3088646,"Address":"Bishop Epifanio B. Surban Street, Poblacion 3, Dumaguete City","OSM_Version":1,"OSM_Changeset":162264624,"OSM_Timestamp":"2025-02-07T23:51:03Z","Check_Date":"2025-02-08","Acquisition_Date":"2026-10-03","Retrieved_On":"2026-10-03","Restroom_Presence":"Unknown","Bidet_Presence":"Unknown","Access":"unknown","Fee":"unknown","Restroom_Verification":"candidate_unverified"}')
ON CONFLICT(canonical_id, source_link_id) DO UPDATE SET
  source_link_id = excluded.source_link_id,
  source_type = excluded.source_type,
  source_record_id = excluded.source_record_id,
  evidence_role = excluded.evidence_role,
  original_name = excluded.original_name,
  original_latitude = excluded.original_latitude,
  original_longitude = excluded.original_longitude,
  original_address = excluded.original_address,
  original_access = excluded.original_access,
  original_fee = excluded.original_fee,
  original_restroom_presence = excluded.original_restroom_presence,
  original_bidet_presence = excluded.original_bidet_presence,
  verification = excluded.verification,
  source_data_json = excluded.source_data_json;
