import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { RESTROOMS } from "../lib/restroom-data.ts";

const outputUrl = new URL(
  "../d1/migrations/0002_seed_restroom_locations.sql",
  import.meta.url,
);

function sqlText(value) {
  return value === null ? "NULL" : `'${value.replaceAll("'", "''")}'`;
}

function rowSql(restroom) {
  return `(${[
    restroom.id,
    sqlText(restroom.name),
    restroom.latitude,
    restroom.longitude,
    sqlText(restroom.address),
    sqlText(restroom.access),
    sqlText(restroom.fee),
    restroom.bidet ? 1 : 0,
    "'candidate'",
    "'imported'",
    "'bundled-catalogue'",
  ].join(", ")})`;
}

export function generateSeedSql(restrooms = RESTROOMS) {
  const ids = new Set();
  const sorted = [...restrooms].sort((left, right) => left.id - right.id);

  for (const restroom of sorted) {
    if (!Number.isInteger(restroom.id) || restroom.id <= 0) {
      throw new Error(`Invalid restroom ID: ${restroom.id}`);
    }
    if (ids.has(restroom.id)) {
      throw new Error(`Duplicate restroom ID: ${restroom.id}`);
    }
    ids.add(restroom.id);
  }

  const header = [
    "-- Generated by scripts/generate-d1-seed.mjs; do not edit by hand.",
    "-- Owner-controlled source rows remain candidates until separately verified.",
    "",
  ];

  const statements = [];
  for (let index = 0; index < sorted.length; index += 100) {
    const batch = sorted.slice(index, index + 100);
    statements.push(
      [
        "INSERT INTO restroom_locations (",
        "  id, name, latitude, longitude, address, access, fee, has_bidet,",
        "  record_status, source_kind, source_reference",
        ") VALUES",
        batch.map(rowSql).join(",\n"),
        "ON CONFLICT(id) DO NOTHING;",
      ].join("\n"),
    );
  }

  return `${header.join("\n")}${statements.join("\n\n")}\n`;
}

const mode = process.argv[2];
const generated = generateSeedSql();

if (mode === "--write") {
  writeFileSync(outputUrl, generated, "utf8");
  console.log(`D1_SEED_WRITTEN rows=${RESTROOMS.length}`);
} else if (mode === "--check") {
  // Normalize CRLF before comparing: Git may check the file out with CRLF on
  // Windows while the generator always emits LF, so a raw byte compare would
  // report a false "stale" result (same convention as the other generators).
  const checkedIn = readFileSync(outputUrl, "utf8").replaceAll("\r\n", "\n");
  if (checkedIn !== generated) {
    throw new Error("D1 seed is stale; run pnpm generate:d1-seed");
  }
  console.log(`D1_SEED_CURRENT rows=${RESTROOMS.length}`);
} else if (fileURLToPath(import.meta.url) === process.argv[1]) {
  throw new Error("Use --write or --check");
}
